Made user selected course names override original course names when available
jtcheng26/canvas-task-extension pull request #105
Opened 2023-10-01 15:49 UTC by rk234

Closes #88 

It looks like the canvas API will add an `original_name` field to courses that have a custom nickname assigned, so I modified `getCourseNames` to check for the existence of that field and return the user's preferred course name instead. Let me know if you would prefer a different approach.

2023-10-02 21:50 UTC, jtcheng26 requested changes
Looks good mostly, I trust you tested it reasonably

2023-10-02 21:50 UTC, jtcheng26 commented on package-lock.json
Prefer to remove these changes from the commit

2023-10-02 21:50 UTC, jtcheng26 commented on src/pages/Content/modules/hooks/useCourseNames.ts
Just checking `course.original_name ? course.name as string : course.course_code as string` would be cleaner

2023-10-03 01:23 UTC, rk234 commented
Thanks, everything should have been addressed now after some wrangling with git.

2023-10-04 20:41 UTC, jtcheng26 approved these changes

2023-10-04 20:58 UTC, rk234 commented
done

2023-10-04 21:18 UTC, jtcheng26 approved these changes

2023-10-04 21:19 UTC, merged