feat: add tooltip to check icons
jtcheng26/canvas-task-extension pull request #121
Opened 2024-01-19 18:35 UTC by TheVanadium

2024-01-19 18:37 UTC, TheVanadium commented
I only tested this in Firefox because that's all I have, so someone should test in Google Chrome and make sure it works.

2024-01-20 00:26 UTC, jtcheng26 requested changes
Looks good, tested it and it works fine in Chrome. Just make sure to run `npm run prettier` and check that `npm run lint` shows no errors

2024-01-20 00:26 UTC, jtcheng26 commented on src/pages/Content/modules/icons/check.tsx
> +  let checkStyleTooltips: CheckStyleTooltips = {
change to const

2024-01-20 02:56 UTC, jtcheng26 approved these changes

2024-01-20 02:57 UTC, merged